---
- name: deploy vsftpd
  hosts: server1.controlm.com
  tasks:
  - name: installation of vsftpd package
    package:
      name: vsftpd
      state: latest
  - name: enable vsftpd
    service:
      name: vsftpd
      enabled: true
  - name: create readme file
    copy:
      content: "Welcome to my friendly server\n"
      dest: /var/ftp/pub/README
      force: no
      mode: 0444



